### ISSUE TITLE
Java implementation can terminate entire application

### ISSUE THREAD

**Issue by tsujamin** [EleanorRagone/anurandom#4]
The way that exceptions are handled in getPage(), namely that it exits the java application, is sub-optimal when used in other applications. An implementation of the methods that allows external exception handling would allow host applications to safely use the class.

As I am using the class in an application I am planning to add this functionality shortly

**Comment by EleanorRagone** [comment]
I assume we're happy with the solution merged in PR 5?  If so, feel free to close this issue.
